version: '3.9'

networks:
  app:
    name: tasks

services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ../:/var/www/dev/
      - ./nginx/logs:/var/log/nginx
    links:
      - app
    networks:
      - app

  app:
    container_name: app
    build: ./app
    restart: always
    links:
      - postgres
    volumes:
      - ../:/var/www/dev/
    networks:
      - app

  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - task_manager_postges_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "task_manager"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - app

volumes:
  task_manager_postges_data:
