version: '3.9'

networks:
  app:
    name: tasks

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ../:/var/www/dev/
      - ./nginx/logs:/var/log/nginx
    links:
      - app
    networks:
      - app
  app:
    build: ./app
    restart: always
    links:
      - postgres
    volumes:
      - ../:/var/www/dev/
    networks:
      - app
  postgres:
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postges_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "storage"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - app
volumes:
  postges_data: